version: '2'
services:
  salt-api:
    build:
      context: "salt_master_docker"
      dockerfile: Dockerfile_stable # Salt-api stable, comment for salt-api develop
      # dockerfile: Dockerfile # Salt-api develop, uncomment for salt-api develop
    ports:
      - 8000:8000
      - 5417:5417
    volumes:
      - ./dist:/code
  saltpad:
    build:
      context: "."
      dockerfile: Dockerfile
    image: saltpad
    ports:
      - 3333:3333
    volumes:
      - .:/usr/src/app
